server:
  port: 8083
  servlet:
    context-path: /api-prestamos
    session:
      timeout: 21600s

spring:
  application:
    name: prestamos
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:postgresql://localhost:5432/dllo_soluciones_prestamos
    username: postgres
    password: root
    hikari:
      poolName: pool

jwt:
  secret: pr12312321ksuo12312321321312312321321l3k1l23jkl21jueba121321
  expiration: 86400000
